# Generated by Django 6.0.6 on 2026-08-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_code', models.CharField(max_length=20, unique=True)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('dept_type', models.CharField(max_length=50)),
                ('hod_name', models.CharField(max_length=100)),
            ],
        ),
    ]
